name: hospital_app
description: Hospital Audit Checklist App
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  provider: ^6.1.1
  intl: ^0.18.1

flutter:
  uses-material-design: true
  assets:
    - assets/checkList.json
